name: Build and Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

    - name: Build and push Docker image
      id: docker_build
      run: |
        docker build . -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/flask-app:${{ github.sha }}
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/flask-app:${{ github.sha }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances
      run: |
        az container create --resource-group CodeAssist --name codeassistance-gem --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/flask-app:${{ github.sha }} --registry-login-server ${{ secrets.AZURE_CONTAINER_REGISTRY }} --registry-username ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --registry-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} --dns-name-label myflaskapp --ports 5000
