name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/your-app-name:latest .
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/your-app-name:latest

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          az container create --resource-group CodeAssist --name codeassistance-gem --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/flask-app:${{ github.sha }} --registry-login-server ${{ secrets.AZURE_CONTAINER_REGISTRY }} --registry-username ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --registry-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} --dns-name-label myflaskapp --ports 5000 --environment-variables @.env